#!/usr/bin/env bash

time (
        # User specified targets
        ninja -C ./build.tmp/clang-debug $* &&
        # Debug builds
        ninja -C ./build.tmp/clang-debug all check &&
        ninja -C ./build.tmp/gcc-debug all check &&
        # Release builds
        ninja -C ./build.tmp/clang-release all check &&
        ninja -C ./build.tmp/gcc-release all check &&
        true
    ) && (
        find ./include/ ./src/ ./test/ -name \*.\?pp -print | xargs clang-format -i
    )
