version: 2.1

executors:
  clang:
    docker:
    - image: kayess/cpp
    environment:
      CC: clang
      CXX: clang++
  clang-libcpp:
    docker:
    - image: kayess/cpp
    environment:
      CC: clang
      CXX: clang++
      CXXFLAGS: "-stdlib=libc++"
      LD_FLAGS: "-stdlib=libc++"
  clang-asan:
    docker:
    - image: kayess/cpp
    environment:
      CC: clang
      CXX: clang++
      CXXFLAGS: "-stdlib=libc++ -fsanitize=address"
      LD_FLAGS: "-stdlib=libc++ -fsanitize=address"
      ASAN_OPTIONS: "alloc_dealloc_mismatch=0"
  gcc:
    docker:
    - image: kayess/cpp
    environment:
      CC: gcc
      CXX: g++
  apple:
    macos:
      xcode: 13.2.1


jobs:
  build:
    parameters:
      compiler:
        type: executor
      variant:
        type: string
    executor: << parameters.compiler >>
    steps:
      - checkout
      - run:
          name: cmake
          command: cmake -G Ninja -S .circleci -B .circleci -DCMAKE_BUILD_TYPE=<< parameters.variant >> $CMAKE_EXTRA -DFELSPAR_ENABLE_IO_URING=NO
      - run:
          name: ninja
          command: ninja -j1 -C .circleci
      - run:
          name: check tests
          command: ninja -j1 -C .circleci felspar-check
      - run:
          name: stress tests
          command: ninja -j1 -C .circleci felspar-stress


workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              compiler: [gcc, clang, clang-libcpp, clang-asan]
              variant: [Debug, Release]
